# Generated by Django 6.1.1 on 2026-09-29 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.BigIntegerField(default=0)),
                ("held", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Sign-up grant"),
                            ("topup", "Demo top-up"),
                            ("hold", "Hold"),
                            ("release", "Hold released"),
                            ("charge", "Charge"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        default=0, help_text="Change to balance, µcr"
                    ),
                ),
                (
                    "held_delta",
                    models.BigIntegerField(default=0, help_text="Change to held, µcr"),
                ),
                ("balance_after", models.BigIntegerField()),
                ("held_after", models.BigIntegerField()),
                ("memo", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="billing.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ledger entries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("held__gte", 0)), name="wallet_held_non_negative"
            ),
        ),
    ]
