# Generated by Django 6.1.1 on 2026-09-29 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_seed_proxy_models"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_request_id", models.UUIDField()),
                ("model_label", models.CharField(max_length=120)),
                ("provider", models.CharField(max_length=16)),
                ("upstream_model", models.CharField(max_length=120)),
                ("input_rate", models.PositiveBigIntegerField()),
                ("output_rate", models.PositiveBigIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("failed", "Failed (not charged)"),
                            ("needs_reconciliation", "Needs reconciliation"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("finish_reason", models.CharField(blank=True, max_length=16)),
                ("error_kind", models.CharField(blank=True, max_length=32)),
                ("error_message", models.CharField(blank=True, max_length=300)),
                (
                    "upstream_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                ("reserved", models.BigIntegerField(help_text="µcr held at start")),
                (
                    "charged",
                    models.BigIntegerField(
                        blank=True, help_text="µcr charged at settlement", null=True
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "overage",
                    models.BooleanField(
                        default=False, help_text="Charge exceeded the reservation"
                    ),
                ),
                ("resolution", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation",
                        to="chat.message",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generations",
                        to="chat.conversation",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.modeloffering",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generations",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="chat_genera_status_650659_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_request_id"),
                        name="generation_unique_request",
                    )
                ],
            },
        ),
    ]
