# Generated by Django 6.1.1 on 2026-09-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=80)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "upstream_model",
                    models.CharField(
                        help_text="Model ID sent to the proxy", max_length=120
                    ),
                ),
                (
                    "input_rate",
                    models.PositiveBigIntegerField(help_text="µcr per 1M input tokens"),
                ),
                (
                    "output_rate",
                    models.PositiveBigIntegerField(
                        help_text="µcr per 1M output tokens"
                    ),
                ),
                ("max_output_tokens", models.PositiveIntegerField(default=2048)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
    ]
